import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MenuCard from "/components/MenuCard";
import data from "/utils/data.js";
import { MobileLayout } from "/components/Layout/MobileLayout";

const bgColors = [
  "#7AB3F333", 
  "#E979B233", 
  "#D7D7F933", 
  "#78F7BB33"
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Advent of CSS - eCommerce component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MobileLayout>
        <main className={styles.main}>
          <h1 className={styles.title}>To Go Menu</h1>
          <ul className={styles.productList}>
            {data.map((item, index: number) => (
              <li key={index}>
                <MenuCard
                  name={item.name}
                  price={item.price}
                  imgUrl={item.imgUrl}
                  bgColor={bgColors[index%4]}
                />
              </li>
            ))}
          </ul>
        </main>
      </MobileLayout>
    </div>
  );
};

export default Home;
