import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { abort } from 'process'
import styles from '../styles/Home.module.css'
import MenuCard from '/components/MenuCard'

const Home: NextPage = () => {
  const menuItems = [
    {
      name: "French Fries with Ketchup",
      price: 4.5,
      picUrl: ''
    },
    {
      name: "Salmon and Vegetables",
      price: 4.5,
      picUrl: ''
    },
    {
      name: "Spaghetti with Meat Sauce",
      price: 4.5,
      picUrl: ''
    },
    {
      name: "French Fries with Ketchup",
      price: 4.5,
      picUrl: ''
    },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Advent of CSS - eCommerce component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          To Go Menu
        </h1>
        <ul className="menu">
          {menuItems.map((item) => (
            <li>
              <MenuCard name={item.name} price={item.price} />
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export default Home
